import Foundation
import SwiftData

/// A single timed line of transcript text. Mirrors the WebVTT cue shape and the
/// Podcasting 2.0 transcript-JSON `segments[].body` shape so we can normalize
/// both formats into one representation that the UI can scrub through.
///
/// `startTime`/`endTime` are seconds from the start of the episode. `speaker`
/// is optional — only the JSON format carries it; VTT cues come in unattributed.
struct TranscriptCue: Codable, Hashable, Sendable {
    var startTime: TimeInterval
    var endTime: TimeInterval
    var speaker: String?
    var text: String
}

/// Persisted on-device transcript for an episode. Generated by
/// `SpeechTranscriptionService` (raw text) OR fetched by
/// `PublishedTranscriptLoader` (timed cues), and looked up by `episodeID` on
/// subsequent loads so we don't have to re-transcribe.
///
/// Keyed by the episode's stable UUID instead of a model relationship so
/// purging an episode doesn't cascade-delete the transcript — useful if the
/// user re-imports the same feed later. Cleanup hook can prune orphans.
@Model
final class EpisodeTranscriptCache {
    @Attribute(.unique) var episodeID: UUID = UUID()
    var text: String = ""
    var generatedAt: Date = Date()
    /// Source flag — "speech" for on-device Speech framework output,
    /// "published" for feed-provided transcripts fetched via
    /// `PublishedTranscriptLoader`. Leaves room for "speechAnalyzer"
    /// (iOS 26 streaming) in future.
    var source: String = "speech"
    /// Approximate duration in seconds the transcript covers — useful when we
    /// later add resume-from-checkpoint partial generation.
    var coverageSeconds: TimeInterval?
    /// Optional BCP-47 language tag, populated from the `language` attribute
    /// on `<podcast:transcript>` when source == "published".
    var language: String?
    /// JSON-encoded `[TranscriptCue]`. Empty string when only flat text is
    /// available (e.g. legacy Speech output, HTML transcript). When non-empty,
    /// the UI can render synchronized line highlighting against playhead.
    private var cuesStorage: String = ""

    init(
        episodeID: UUID,
        text: String,
        generatedAt: Date = .now,
        source: String = "speech",
        coverageSeconds: TimeInterval? = nil,
        language: String? = nil,
        cues: [TranscriptCue] = []
    ) {
        self.episodeID = episodeID
        self.text = text
        self.generatedAt = generatedAt
        self.source = source
        self.coverageSeconds = coverageSeconds
        self.language = language
        self.cuesStorage = Self.encodeCues(cues)
    }

    var cues: [TranscriptCue] {
        get { Self.decodeCues(cuesStorage) }
        set { cuesStorage = Self.encodeCues(newValue) }
    }

    private static let cuesEncoder = JSONEncoder()
    private static let cuesDecoder = JSONDecoder()

    static func encodeCues(_ cues: [TranscriptCue]) -> String {
        guard !cues.isEmpty,
              let data = try? cuesEncoder.encode(cues),
              let string = String(data: data, encoding: .utf8) else {
            return ""
        }
        return string
    }

    static func decodeCues(_ storage: String) -> [TranscriptCue] {
        guard !storage.isEmpty,
              let data = storage.data(using: .utf8),
              let cues = try? cuesDecoder.decode([TranscriptCue].self, from: data) else {
            return []
        }
        return cues
    }
}
