import Foundation
import SwiftData

/// Persisted on-device transcript for an episode. Generated by
/// `SpeechTranscriptionService` and looked up by `episodeID` on subsequent
/// loads so we don't have to re-transcribe (a 30-min episode takes 60-90s of
/// real time even on-device).
///
/// Keyed by the episode's stable UUID instead of a model relationship so
/// purging an episode doesn't cascade-delete the transcript — useful if the
/// user re-imports the same feed later. Cleanup hook can prune orphans.
@Model
final class EpisodeTranscriptCache {
    @Attribute(.unique) var episodeID: UUID = UUID()
    var text: String = ""
    var generatedAt: Date = Date()
    /// Source flag — "speech" today, leaves room for "speechAnalyzer"
    /// (iOS 26 streaming) or "official" import in future.
    var source: String = "speech"
    /// Approximate duration in seconds the transcript covers — useful when we
    /// later add resume-from-checkpoint partial generation.
    var coverageSeconds: TimeInterval?

    init(
        episodeID: UUID,
        text: String,
        generatedAt: Date = .now,
        source: String = "speech",
        coverageSeconds: TimeInterval? = nil
    ) {
        self.episodeID = episodeID
        self.text = text
        self.generatedAt = generatedAt
        self.source = source
        self.coverageSeconds = coverageSeconds
    }
}
